[versions]
agp = "8.5.0"
kotlin = "1.9.0"
coreKtx = "1.10.1"
mavenplugin = "2.1"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }

[plugins]
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
com-github-dcendents = {id = "android-maven-gradle-plugin", version.ref = "mavenplugin"}

